apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: owncloud-ingress
spec:
  rules:
  - host: owncloud.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: owncloud
            port:
              number: 80
